version: '3.8'

services:
  backend:
    build: ./backend
    container_name: role_bot_backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend:/app
    # Добавляем чтение переменных окружения из файла .env в папке backend
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./frontend
    container_name: role_bot_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
